services:
  - type: web
    name: kniha-jizd
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run_render.py
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
